//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using Microsoft.AspNet.Identity;

namespace ProjektniCentarSkole
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Skola
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skola()
        {
            this.KontaktOsobas = new HashSet<KontaktOsoba>();
        }
    
        public int Id { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "Naziv skole mora biti najmanje {2} znakova dug", MinimumLength=6)]
        [DataType(DataType.Text)]
        [Display(Name = "Naziv skole")]
        public string NazivSkole { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "Adresa skole mora biti najmanje {2} znakova duga", MinimumLength = 6)]
        [DataType(DataType.Text)]
        [Display(Name = "Adresa skole")]
        public string AdresaSkole { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Opstina { get; set; }


        [Required]
        [DataType(DataType.Text)]
        [RegularExpression("^[0-9]{5}$", ErrorMessage = "Postanski broj se sastoji od 5 cifara")]
        [Display(Name = "Postanski broj")]

        public Nullable<int> PostanskiBroj { get; set; }


        [Required]
        [StringLength(8,ErrorMessage = "Maticni broj se mora sastojati od 8 cifara", MinimumLength = 8)]
        [DataType(DataType.Text)]
        [RegularExpression("^[0-9]{8}$", ErrorMessage = "Maticni broj se mora sastojati od 8 cifara")]
        [Display(Name = "Maticni broj")]
        public string MaticniBroj { get; set; }

        [Required]
        [StringLength(9, ErrorMessage = "PIB se mora sastojati od 9 cifara", MinimumLength = 9)]
        [DataType(DataType.Text)]
        [RegularExpression("^[0-9]{9}$", ErrorMessage = "PIB se mora sastojati od 9 cifara")]
        public string PIB { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [RegularExpression("^[0-9-]*$", ErrorMessage = "Broj racuna ne sme sadrzati slova")]
        [Display(Name = "Broj racuna")]
        public string BrojRacuna { get; set; }

        [Required]
        [DataType(DataType.Url, ErrorMessage = "Ispravan unos za web stranicu je: http://www.its.edu.rs/")]
        [Display(Name = "Web stranica skole")]
        public string WebStranica { get; set; }

        
        [DataType(DataType.Text)]
        public string Pecat { get; set; }


        [StringLength(300, ErrorMessage = "Beleska moze biti najvise {1} znakova duga")]
        [DataType(DataType.Text)]
        public string Beleska { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KontaktOsoba> KontaktOsobas { get; set; }
    }
}
