//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Net.Cache;

namespace ProjektniCentarSkole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefon
    {
        public int Id { get; set; }
        public string Oznaka { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression("^[0-9+-]*$", ErrorMessage = "Ne smete unositi slova za broj telefona")]
        public string Broj { get; set; }

        public string Lokal { get; set; }
        public Nullable<int> IdKontaktOsoba { get; set; }
    
        public virtual KontaktOsoba KontaktOsoba { get; set; }
    }
}
